# Generated by Django 3.0.3 on 2020-02-14 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('minutes', models.TextField(blank=True, null=True)),
                ('zoom_link', models.URLField(blank=True, null=True)),
                ('is_accepted', models.BooleanField()),
                ('is_slack', models.BooleanField()),
                ('date_and_time', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='participating_meetups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=255)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.Meetup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
