# Generated by Django 3.0.3 on 2020-02-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200214_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='is_slack',
            field=models.BooleanField(default=False),
        ),
    ]
