# Generated by Django 3.0.3 on 2020-02-14 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200214_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 10, 24, 48, 963928)),
        ),
    ]
