# Generated by Django 3.0.3 on 2020-02-14 12:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200214_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 29, 21, 703380)),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.Meetup')),
            ],
        ),
    ]
