# Generated by Django 3.0.3 on 2020-02-14 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200214_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 35, 38, 483253)),
        ),
    ]
