# Generated by Django 3.0.3 on 2020-02-14 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200214_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 18, 37, 43, 399927)),
        ),
    ]
